# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Prabhudayal Acharya
title: Senior Software Engineer
email: prabhudayala@gmail.com

# Social links
twitter_username: prabhudayala
github_username:  prabhudayala
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: prabhudayala
linkedin_username: prabhudayala
# pinterest_username: jekyll
youtube_username: prabhudayala
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Prabhudayal Acharya and I'm a Senior Software Engineer at Mindtree. I have 4.5 years of experience.

  I am most skilled in: <mark>Machine Learning</mark> and <mark>Python</mark>. I have moderate experience in <mark>Deep Learning</mark> too.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Artificial Intelligence and Machine Learning my interests and hobbies are:
   - Cycling
   - Gaming
   - Indian Mythology

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true/false
